services:
  mongodb:
    image: mongo:6.0
    container_name: hospital_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: hospital_redis
    ports:
      - "6380:6379"

volumes:
  mongo_data: