version: '3.8'

services:
  # --- INFRAESTRUCTURA ---
  mongodb:
    image: mongo:6.0
    container_name: hospital_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: hospital_redis
    ports:
      - "6380:6379"

  # --- Ingreso Hospital ---
  servidor_python:
    build: .
    container_name: hospital_server
    ports:
      - "8888:8888"
    environment:
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
      - REDIS_PORT=6379  
    depends_on:
      - mongodb
      - redis
    command: python3 servidor/main.py

  celery_worker:
    build: .
    container_name: hospital_worker
    environment:
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    command: celery -A workers.celery_app worker --loglevel=info

volumes:
  mongo_data: